HW3 Done
KONOHA-GANGSTA/react_app pull request #4
Opened 2023-11-21 13:30 UTC by KONOHA-GANGSTA

2023-11-23 11:56 UTC, SArchieEdu requested changes

2023-11-23 11:56 UTC, SArchieEdu commented on src/components/Restaurants/component.jsx
> +export const Restaurants = ({ restaurants, selectedRestaurant }) => {
теперь отображаем только один ресторан, поэтому компонент Restaurants совсем не нужен

2023-11-30 13:56 UTC, ArchieSA approved these changes
После правок можно мерджить. Посмотрите как в разборе сделано

2023-11-30 13:56 UTC, ArchieSA commented on src/components/Restaurant/component.jsx
> +export const Restaurant = ({ restaurants, selectedRestaurant }) => {
этот компонент принимает только один ресторан и ничего не знает про какой-то выбор. Сейчас он жестко завязан на табы, так лучше не делать.

2023-12-01 21:24 UTC, merged